### ISSUE TITLE
Issue in step 2 ipyrad (filtering)

### ISSUE THREAD

**Issue by YaraAlshw** [YaraAlshw/finalproject#3]
https://github.com/YaraAlshw/finalproject/blob/3c937285394a0b03cf20abc7cc3385e474578f03/s2_error_log.txt#L2

I'm at step 2 (filtering and trimming) of ipyrad. After the step completed, I received an error in the output text file. It seems like the command cutadapt didn't work correctly. This is an example of the error I received, which seems to repeat and occur for every .fastq file I have (the text file is referenced above):

\ncutadapt: error: Error in FASTQ file at line 26144121: Line expected to start with '@', but found '\\n'\n")

I manually examined one of my .fastq files, and this is an example of the first few lines:

@SRR9036111.1.1 8_2209_1356_2096 length=118
TGCAGGAACGCTATGGACACCCTTTCCGCCCAAAGCCTACGTAATAGTTGTGCGCGTTTCTCAGGTAAATTGAGACCCCTGACATTGTGGGACCACAGATTAAGATCGGAAGAGCACA
+SRR9036111.1.1 8_2209_1356_2096 length=118
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFF
@SRR9036111.2.1 8_2209_1728_2044 length=118
TGCAGGGTCTAGCAAGCTGTTAACAGAGCAGGAGATACAACATTTTAAGGGCAGTTACATAGGATTTTCCTGAGGCTGCATTCGATCTTAAGATCGGAAGAGCACACGTCTGAACTCC
+SRR9036111.2.1 8_2209_1728_2044 length=118
</</<FFFF/FFB<BBBB//</<<///</<<//</BF<FFF/FF/FBFBB</FF////<//F<//</<F/<//<BFB//F<<///<F<BB///</<///7/<B/FFF7F/7/7F///B

I tried searching for the '\\n'\n" term but my text editor kept crashing.

**Comment by lemellenthin** [comment]
Hey Yara,

I just wanted to follow up on our meeting during office hours today. How did getting rid of the blank spaces go? Some useful links I found to help with this error are (https://github.com/squizlabs/PHP_CodeSniffer/issues/2554 and https://stackoverflow.com/questions/2369440/how-to-delete-all-blank-lines-in-the-file-with-the-help-of-python) and if you were to use regular expressions to loop through all the files and delete the blank spaces (what it is reading as /n), here is a quick tutorial (https://www.digitalocean.com/community/tutorials/using-grep-regular-expressions-to-search-for-text-patterns-in-linux).

Let me know if this helps or if there is another problem!

**Comment by YaraAlshw** [comment]
Hi Lauren,
I deleted the empty lines with this command: **grep -v '^[[:space:]]*$' sra_data.fastq  > sra_data2.fastq** and then I tried running step 2 in ipyrad using only 3 fastq files to try it out, and it worked!! thanks so much for helping me with this. I will look into the regular expression link you sent to try ti loop it through all the files at once instead of me manually doing it on each individual file.
